version: 0.0
os: linux
files:
  - source: LibrarySystem.war
    destination: /opt/tomcat/webapps
hooks:
  ApplicationStop:
    - location: stopApplication.sh
      timeout: 300
      runas: centos
  AfterInstall:
    - location: startApplication.sh
      timeout: 300
      runas: centos
