version: 0.0
os: linux
files:
      - source: LibrarySystem.war
      destination: /var
hooks:
BeforeInstall:
    - location: /opt/tomcat/bin/shutdown.sh
      timeout: 300
      runas: centos 
ApplicationStart:
    - location: /opt/tomcat/bin/startup.sh
      timeout: 300
      runas: centos
