version: 0.0
os: linux
files:
  - source: LibrarySystem.war
    destination: /opt/tomcat/webapps
  - source: startApplication.sh
    destination: /tmp/
    
hooks:
AfterInstall:
    - location: ./startApplication.sh
      timeout: 300
      runas: centos
