version: 0.0
os: linux
files:
  - source: LibrarySystem.war
    destination: /opt/tomcat/webapps
hooks:
ApplicationStart:
    - location: infrastructure/aws/codedeploy/startApplication.sh
      timeout: 300
      runas: centos
