version: 0.0
os: linux
files:
  - source: LibrarySystem.war
    destination: /opt/tomcat/webapps
  - source: cloudwatch-config.json
    destination: /opt

hooks:
  ApplicationStop:
    - location: stopApplication.sh
      timeout: 350
      runas: centos
  AfterInstall:
    - location: startApplication.sh
      timeout: 350
      runas: centos
