version: 0.0
os: linux
files:
      - source: LibrarySystem.war
destination: /opt/tomcat/webapps
hooks:
ApplicationStart:
    - location: /opt/tomcat/bin/startup.sh
      timeout: 300
      runas: centos
